language: java

jdk:
  - oraclejdk8

sudo: false

## export GPG details
before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
  - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

addons:
  sonarcloud:
    organization: "ibanity"
    token:
      secure: "C3xBA7ViC9ORDVFIYq0eDvOl3TUkFq+9AuF6bJe1h/e3UcpBMp2YB6NFnuUVBm8/FLwgaB7cdi5YJA6KT1GGw0DXkQgYfNJRyuDJMhthyzCMUpCrT08xwt5GszQ5bIfDQhAwjhJdjnLeA7PKBXYnScS0+MGjm9yYdcNbUegkvgonVm1JxxEwW3Wz7m/6ohumY3d/1m2INqPevHGcfYJAslZ3OFY1s3mnC7gD5vWacbHKCQE3tFxTtjOG9zzaysbu2FWivWFgucFqZznXK98eitSdAyR9eUOuLSZtqUGJR0sW0nIhc8fBOwRtgQIpPaymzYf51FqX8oPPAmkXJRwjhlTakk+mVtoKVmp/BMq2QZkmLvRYKkWelBKxP9V8W0GFxOqmAotvyAA44X9mMOP+7CloIQ7Cf38xv5JMSMjZwE6aUspvlsAbKiKtvw+ztHdOJJadmBrfxb8U+3bOVSnMebV2YfBsY1FCrZpmovl9FH/gb6thUSGdpMU7eF6TVdPEbKVMdGmdLn9nfyVPlrnJz1I8TR4HrHSH6lIYf4gatgEfOHCaKn/KMqGxqieCsy55+d2NYSVGY9S4z1okHjcELUSZ+mTBN0Os9zfMDMGR4X+8W2QG01gR/Rima9KEKVutOXTDOWO2lr48DFyQ3Agc2rhEkoQqbJN8bIZnHIhj0Lk="

cache:
  directories:
    - ~/.m2/repository
    - ~/.sonar/cache

after_success:
  - bash ./travis-ci/deploy.sh